### ISSUE TITLE
Blurry label content

### ISSUE THREAD

**Issue by TonciGitHub** [alekseyn/EasyTableView#27]
Hello

First of all thank U very much for this peace of code...

After transforming the tableview, newly created coordinates don't have integer vals so the content of the tableview becomes blurry. I suggest some type of rounding new coordinate and size values after performing the transform operation 
in 
- (void)createTableWithOrientation:(EasyTableViewOrientation)orientation {

**Comment by alekseyn** [comment]
EasyTableView was just recently updated. The interface has changed slightly so you may need to make changes to your code to support EasyTableView 2.0. Please update and let me know if the same behavior still exists. Thanks.
