### ISSUE TITLE
Loading Views during animation

### ISSUE THREAD

**Issue by azplanlos** [alekseyn/EasyTableView#28]
I have a horizontal scrolling EasyTableView with a couple of UIImageViews with no user interaction. I scroll the content of my EasyTableView by using:

[UIView animateWithDuration:10 animations:^{ [easyTableView setContentOffset:CGPointMake(500, 0) animated:NO];}];

but when new views get loaded during this animation scroll I see the Images rotating into position slowly.

**Comment by alekseyn** [comment]
EasyTableView was just recently updated. The interface has changed slightly so you may need to make changes to your code to support EasyTableView 2.0. Please update and let me know if the same behavior still exists. Thanks.
