### ISSUE TITLE
Repeated select of same table view cell

### ISSUE THREAD

**Issue by greenwoodcm** [alekseyn/EasyTableView#31]
Even if you explicitly deselect a table view cell in the delegate method, repeated select of a cell at the same index path does not work.  This is the case even if the cell at that index path is not the same.

**Comment by alekseyn** [comment]
EasyTableView was just recently updated. The interface has changed slightly so you may need to make changes to your code to support EasyTableView 2.0. Please update and let me know if the same behavior still exists. Thanks.
