### ISSUE TITLE
How to set footerview

### ISSUE THREAD

**Issue by thejeraldo** [alekseyn/EasyTableView#36]
How can I set the footer view? I tried using the tableView.footerView property but this is not what I need.

**Comment by alekseyn** [comment]
EasyTableView was just recently updated. The interface has changed slightly so you may need to make changes to your code to support EasyTableView 2.0. Please update and let me know if the same behavior still exists. Thanks.

**Comment by alekseyn** [comment]
No follow-up response. If this is still an issue, please post a new comment.
