### ISSUE TITLE
is it working in iOS8?

### ISSUE THREAD

**Issue by kasas** [alekseyn/EasyTableView#40]
Hi,

I have implemented a viewpager using EasyTableView, however when I try to execute it in iOS8 (iphone5 and iPad) it is not working. I began making tests with iOS7 and it worked like a charm!!

Thanks!

**Comment by abhimanyu1289** [comment]
Is it working in iOS8?

**Comment by abhimanyu1289** [comment]
The demo seems to be working with target as iOS 8.3 SDK

**Comment by alekseyn** [comment]
EasyTableView was just recently updated. The interface has changed slightly so you may need to make changes to your code to support EasyTableView 2.0. Please update and let me know if the same behavior still exists. Thanks.
