### ISSUE TITLE
Cannot compile with Xcode 8

### ISSUE THREAD

**Issue by lukitnev** [alekseyn/EasyTableView#44]
Man, thank you for good lib, but now I cannot compile pod with Xcode 8 (last version). Minimal target is iOS 7.0 and maximum is 10.0.
Please, can you recompile lib for last version of iOS|Xcode, fast as you can?

From Xcode command line:
`ld: warning: directory not found for option '-L/Users/im/Library/Developer/Xcode/DerivedData/OptWear-Mobile-asxkvsgbgcvvjkekgtosoiafrawg/Build/Products/Debug-iphonesimulator/EasyTableView'`

`ld: library not found for -lEasyTableView`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by alekseyn** [comment]
Hmm, not sure what the problem is. I can build the project successfully without error with Xcode 8. Sometimes deleting the DerivedData folder clears up lingering issues.

**Comment by lukitnev** [comment]
Ok, I was delete this path, but error steel exist. And I don't know - why. All paths are good in Build Settings -> Library search paths

**Comment by alekseyn** [comment]
Sounds like you are having a general build problem, unrelated to EasyTableView. If your project is not very complicated, try creating a new empty project from Xcode 8, and then copy/move your source into the new project.

**Comment by lukitnev** [comment]
Okay, I will try some methods.

**Comment by lukitnev** [comment]
Before upgrading Xcode to v.8, all works fine. :(

**Comment by lukitnev** [comment]
I found the reason. Who have problems as mine, must set "Build Active Architecture Only" to "NO" at TARGET -> Build Phases (Your project target and ALL pods target).

**Comment by alekseyn** [comment]
I'm glad you find a solution. Thank you for the update!
